spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tttn_database?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 231078
    initialization-mode: always
  mail:
    host: smtp.gmail.com
    username: thuy.le2@ntq-solution.com.vn
    password: thuy231078
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename:validation
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: false
        enable_lazy_load_no_trans: true

    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
server.error.include-stacktrace: never
file:
  upload-dir:
    ./upload
server:
  port: 8888




