spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 231078
    initialization-mode: always


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        enable_lazy_load_no_trans: true

    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
server.error.include-stacktrace: never
file:
  upload-dir:
    ./upload
server:
  port: 8888



